application:
  title: KR Simple application
  description: Application description for this one
  logback:
    access:
      config:
        path: logback-access.xml

---
server:
  port: 8080
spring:
  profiles: local
swagger:
  enabled: true

---
server:
  port: 8080
spring:
  profiles: dev
swagger:
  enabled: true

---
server:
  port: 8080
spring:
  profiles: prod
swagger:
  enabled: true
